apiVersion: v1
kind: Service
metadata:
  name: retail-segmentation
  labels:
    run: retail-segmentation
  namespace: retail
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: retail-segmentation
  sessionAffinity: ClientIP # Configure session affinity so that requests from the same client are always routed to the same pod