apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: {{ include "retail.fullname" . }}
  labels:
  {{- include "retail.labels" . | nindent 4 }}
resources:
- namespace.yaml
- deployment.yaml
- service.yaml